version: "3.8"

services:
  documind-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: documind-be:1.0.0
    container_name: documind-api
    env_file:
      - ${ENV_FILE:-.env.development}
    depends_on:
      #- sql-db
      - postgres
      - qdrant

    networks:
      - documind-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: documind-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - documind-api
    networks:
      - documind-network
    restart: unless-stopped

  #sql-db:
  #  image: mcr.microsoft.com/mssql/server:2022-latest
  #  container_name: documind-db
  #  env_file:
  #    - ${ENV_FILE}
  #  ports:
  #    - "1433:1433" # dev only
  #
  #  volumes:
  #    - mssql-data:/var/opt/mssql
  #  networks:
  #    - documind-network
  #  restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: documind-db
    env_file:
      - ${ENV_FILE:-.env.development}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - documind-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: documind-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - documind-network
    restart: unless-stopped

networks:
  documind-network:
    driver: bridge

volumes:
  #mssql-data:
  postgres-data:
  qdrant-data:
